### ISSUE TITLE
Review class name

### ISSUE THREAD

**Issue by extsoft** [ahrech/pbc-ahrech#6]
https://github.com/ahrech/pbc-ahrech/blob/d94c37a6ffabcd3c4cc4d1ad34d04daff1ad1deb/pbc/sg/sg.py#L62

**Comment by ahrech** [comment]
@extsoft Could you please clarify the issue a bit more? I'm not sure what's wrong with the name.

**Comment by extsoft** [comment]
Start.. ?? Maybe Smart?

**Comment by ahrech** [comment]
@extsoft Thanks for the clarification. I've fixed the name. But it was an exact copy from the [Day 6 Logs](https://gist.github.com/extsoft/0a7861abc8459e180c26106a0e4238f0#file-day6-md) :)
